# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site favicons & manifest icons
# 9. Site navigation
# TODO: HelloWorld
# 1. Files excluded from Jekyll builds
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- Gemfile
- Gemfile.lock
- alembic-jekyll-theme.gemspec
- .jekyll-cache

# 2. Installed Gems
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji

# 3. Gem settings
paginate: 2 # jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page
# jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
# twitter:
#   username: de_hofakker # jekyll-seo-tag > Owners twitter username
author: SchoolDeHofakker # jekyll-seo-tag > default author
# social: # jekyll-seo-tag > social overrides
#   name: David Darnes # jekyll-seo-tag > real name
  # links:  # jekyll-seo-tag > social aliases (sameAs)
    # - https://twitter.com/DavidDarnes
    # - https://www.facebook.com/daviddarnes
    # - https://www.linkedin.com/in/daviddarnes
    # - https://plus.google.com/+DavidDarnes
    # - https://github.com/daviddarnes
# markdown: CommonMark # Markdown parse settings, CommonMark performs slightly better an others in build time
# commonmark:
  # options: ["SMART", "FOOTNOTES"]
  # extensions: ["strikethrough", "autolink", "table"]

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Europe/Amsterdam # Timezone for blog posts and alike

# 5. Collections
collections:
  posts:
    title: Nieuws # Needed for Siteleaf
    output: true
    description: "Nieuwsberichten, aankondigingen en wetenswaardigheden van de Hofakker" # The post list page content
    feature_image: "/assets/banner_nieuws.jpg"

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
    values:
      image: "/assets/default-social-image.png" # Default image for sharing

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
lang: nl-NL # Set the site language
title: "School de Hofakker" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/logos/logo.svg" # Site logo, also used in jekyll-seo-tag
description: "Kleinschalig onderwijs dicht bij de natuur vanuit een antroposofisch mensbeeld" # Site description and default description, also used in jekyll-seo-tag
destination: ./build
url: "https://schooldehofakker.nl" # Site url, also used in jekyll-seo-tag
baseurl: ""
repo: "https://github.com/schooldehofakker/schooldehofakker.nl"
email: "contact@schooldehofakker.nl"
# disqus: "alembic-1" # Blog post comments, uncomment the option and set the site ID from your Disqus account
google_analytics: 'UA-11677999-17'
# service_worker: false # Will turn off the service worker if set to false
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference

# 8. Site favicons & manifest icons
favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
  16: '/assets/logos/logo@16px.png'
  32: '/assets/logos/logo@32px.png'
  96: '/assets/logos/logo@96px.png'
  120: '/assets/logos/logo@120px.png'
  144: '/assets/logos/logo@144px.png'
  180: '/assets/logos/logo@180px.png'
  512: '/assets/logos/logo@512px.png'
  1024: '/assets/logos/logo@1024px.png'

# 9. Site navigation
navigation_header:
  Home: /
  # Elements: /elements/
  Onze Kracht: /kracht-van-de-hofakker/
  Onze Leraren: /leraren/
  Vacatures: /vacatures/
  Nieuws: /nieuws/
  # Donaties: /donaties/
  # Categorieën: /categorieën/
  Zoeken: /zoeken/
  Contact: /contact/

navigation_footer:
  Kleinschalig onderwijs dicht bij de natuur vanuit een antroposofisch mensbeeld

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  # Twitter: https://twitter.com/de_hofakker
  # LinkedIn: https://www.linkedin.com/in/daviddarnes
  # Google+: https://plus.google.com/+DavidDarnes
  GitHub: https://github.com/schooldehofakker/schooldehofakker.nl
  FaceBook: https://www.facebook.com/schooldehofakker/
  Instagram: https://www.instagram.com/schooldehofakker/
  link: https://schooldehofakker.nl
  RSS: /feed.xml

sharing_links:
  Twitter: "#0d94e7"
  Facebook: "#3B5998"
  Email: "info@schooldehofakker.nl"
