default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default
  database: hofakker_development

test:
  <<: *default
  database: hofakker_test

staging:
  <<: *default
  database: hofakker_staging

production:
  <<: *default
  database: hofakker_production
