meta_title: "School de Hofakker"
meta_description: "De Hofakker is een school waar kinderen met rode wangen en lichtjes in hun ogen uit school komen. De lessen worden zo ingericht dat het kind zichzelf kan verbinden met de wereld om hem of haar heen en tegelijkertijd het eigen levensdoel trouw kan blijven. Buiten zijn wordt afgewisseld met binnen zitten, om aan de natuurlijke behoefte van bewegen tegemoet te komen. Van buiten zijn en bewegen krijg je weer nieuwe energie!"
meta_image: "logo.png"
twitter_account: "@hofakker"
