# This is an example with only required properties:
version: 1
update_configs:
  - package_manager: "ruby:bundler"
    directory: "/"
    update_schedule: "live"
    default_reviewers:
      - "blijblijblij"
    default_labels:
      - "dependencies"
    target_branch: "master"
