name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - '2.6.x'
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup System
        run: |
          sudo apt-get install libsqlite3-dev
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Bundle
        run: |
          export BUNDLE_GEMFILE="Gemfile"
          gem uninstall -aIx bundler
          gem install bundler -v 1.17.3
          bundle install --jobs 4 --retry 3
      - name: Test
        run: jekyll build -d docs && ls -al docs/
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - '2.6.x'
    steps:
      - name: Build
        run: jekyll build -d docs && ls -al docs/
  deploy:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@master
      env:
        FTP_SERVER: ${{secrets.FTP_SERVER}}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        LOCAL_DIR: docs
        REMOTE_DIR: Website_2019_nieuwe_stijl
        ARGS: --delete
        # --delete arg will delete files on the server if you've deleted them in git
