name: Jekyll Deploy

on: [push]

jobs: 
  verify:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11.1
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: ktsjing_test
          POSTGRES_PASSWORD: ""
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.5

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.15.0

      - name: Install dependencies
        run: |
          # fix: Unable to fetch some archives
          sudo apt-get update
          sudo apt-get -yqq install libpq-dev chromium-chromedriver
          gem install bundler
          bundle install

      - name: Run Rubocop
        run: bin/rubocop

      - name: Run tests
        run: bin/rspec

  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build & Deploy to GitHub Pages
        env: 
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_SCHOOL }}
          GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
        uses: BryanSchuetz/jekyll-deploy-gh-pages@master
